type EvaluationAvg {
  questionTitle: String!
  totalSum: Int!
  sum: Int!
  avg: String!
  score: String!
  isExpert: Boolean!
  isManager: Boolean!
}

type Query {
  getAllEval: [Evaluation!]!
  getSelectEvaluation(id: String!): [Evaluation!]!
  getAvgData(id: String!): Int!
  getEvaluationAvg01(round: Int!): [EvaluationAvg]!
  getEvaluationAvg02(round: Int!): [EvaluationAvg]!
}

type Mutation {
  createEvaluation(
    userKey: String
    questionKey: String!
    score: Int!
    description: String!
  ): Boolean!

  deleteEvaluation(list: [String!]!): Boolean!
}
