type User {
  id: ID!
  round: Int!
  username: String!
  mobileNumber: String!
  isExpert: Boolean!
  isComplete: Boolean
  createdAt: String!
  updatedAt: String!
}

type AcceptRecord {
  id: ID!
  date: String!
}

type Question {
  id: ID!
  round: Int!
  quetionTitle: String!
  sort: Int!
  createdAt: String!
  updatedAt: String!
}

type Evaluation {
  id: ID!
  user: User!
  question: Question!
  score: Int!
  description: String!
  createdAt: String!
  updatedAt: String!
}

type EvaluationAvg {
  value: String!
  percent: Int!
}

type Streaming {
  id: ID!
  key: String!
  createdAt: String!
  updatedAt: String!
}
